name: plebqr_india
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  equatable: ^2.0.8
  json_annotation: ^4.9.0
  meta: ^1.16.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  easy_stepper: ^0.8.5+1
  formz: ^0.8.0
  auto_size_text: ^3.0.0
  routemaster: ^1.0.1
  flutter_bloc: ^9.1.1
  bolt11_decoder: ^1.0.2
  image_picker: ^1.2.1
  mobile_scanner: ^7.1.4
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  confetti: ^0.8.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Fondamento
      fonts:
        - asset: assets/Fondamento-Regular.ttf
